---
- hosts: all
  become: true
  pre_tasks:

  - name: update ubuntu cache
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  roles:
    - NTP
    - OpenS
    - SQLdb
    - msgQ
    - Mcached
    - Etcd
